package gui;
import dao.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tohfi140
 */

public class MainMenu extends javax.swing.JFrame {
     final PaperDAO Pdao;
     final TutorDAO Tdao;
     final LibraryDAO Ldao;
     final HallDAO Hdao;
    	
     /**
	 * Creates new form MainMenu
	 */
         

    public MainMenu(PaperDAO Pdao, TutorDAO Tdao, LibraryDAO Ldao, HallDAO Hdao) {
        this.Pdao = Pdao;
        this.Tdao = Tdao;
        this.Ldao = Ldao;
        this.Hdao = Hdao;
        initComponents();
    }

   
       
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        newTutor = new javax.swing.JButton();
        viewTutor = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        viewPaper = new javax.swing.JButton();
        newHall = new javax.swing.JButton();
        newPaper = new javax.swing.JButton();
        viewHall = new javax.swing.JButton();
        newLibrary = new javax.swing.JButton();
        viewLibrary = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Otago Student Review Administration");
        jLabel1.setName("jLabel1"); // NOI18N

        newTutor.setText("Add Tutor");
        newTutor.setName("newTutor"); // NOI18N
        newTutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTutorActionPerformed(evt);
            }
        });

        viewTutor.setText("View Tutors");
        viewTutor.setName("viewTutor"); // NOI18N
        viewTutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTutorActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.setName("exitButton"); // NOI18N
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        viewPaper.setText("View Papers");
        viewPaper.setName("viewPaper"); // NOI18N
        viewPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPaperActionPerformed(evt);
            }
        });

        newHall.setText("Add Hall");
        newHall.setName("newHall"); // NOI18N
        newHall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newHallActionPerformed(evt);
            }
        });

        newPaper.setText("Add Paper");
        newPaper.setName("newPaper"); // NOI18N
        newPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPaperActionPerformed(evt);
            }
        });

        viewHall.setText("View Halls");
        viewHall.setName("viewHall"); // NOI18N
        viewHall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewHallActionPerformed(evt);
            }
        });

        newLibrary.setText("Add Library");
        newLibrary.setName("newLibrary"); // NOI18N
        newLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newLibraryActionPerformed(evt);
            }
        });

        viewLibrary.setText("View Library");
        viewLibrary.setName("viewLibrary"); // NOI18N
        viewLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewLibraryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 130, Short.MAX_VALUE)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newTutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(newHall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewHall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(viewLibrary, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(newLibrary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newPaper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewPaper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newTutor)
                    .addComponent(newPaper))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewTutor)
                    .addComponent(viewPaper))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newHall)
                    .addComponent(newLibrary))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewHall)
                    .addComponent(viewLibrary))
                .addGap(14, 14, 14)
                .addComponent(exitButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void newTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTutorActionPerformed
      // TODO add your handling code here:
      TutorEditor dialouge = new TutorEditor(this, true, Tdao, Pdao);
      dialouge.setLocationRelativeTo(this);
      dialouge.setVisible(true);
   }//GEN-LAST:event_newTutorActionPerformed

   private void viewTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTutorActionPerformed
      // TODO add your handling code here:
      TutorViewer dialouge = new TutorViewer(this,true,Tdao, Pdao);
      dialouge.setLocationRelativeTo(this);
      dialouge.setVisible(true);
   }//GEN-LAST:event_viewTutorActionPerformed

   private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
      // TODO add your handling code here:
		System.exit(0);
   }//GEN-LAST:event_exitButtonActionPerformed

    private void viewPaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPaperActionPerformed
      PaperViewer dialouge = new PaperViewer(this,true,Pdao);
      dialouge.setLocationRelativeTo(this);
      dialouge.setVisible(true);
    }//GEN-LAST:event_viewPaperActionPerformed

    private void newHallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newHallActionPerformed
      HallsEditor dialouge = new HallsEditor(this,true,Hdao);
      dialouge.setLocationRelativeTo(this);
      dialouge.setVisible(true);
    }//GEN-LAST:event_newHallActionPerformed

    private void viewHallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewHallActionPerformed
      HallsViewer dialouge = new HallsViewer(this,true,Hdao);
      dialouge.setLocationRelativeTo(this);
      dialouge.setVisible(true);
    }//GEN-LAST:event_viewHallActionPerformed

    private void newPaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPaperActionPerformed
      PaperEditor dialouge = new PaperEditor(this,true,Pdao);
      dialouge.setLocationRelativeTo(this);
      dialouge.setVisible(true);
    }//GEN-LAST:event_newPaperActionPerformed

    private void newLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newLibraryActionPerformed
      LibraryEditor dialouge = new LibraryEditor(this,true,Ldao);
      dialouge.setLocationRelativeTo(this);
      dialouge.setVisible(true);
    }//GEN-LAST:event_newLibraryActionPerformed

    private void viewLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewLibraryActionPerformed
        LibraryViewer dialouge = new LibraryViewer(this,true,Ldao);
        dialouge.setLocationRelativeTo(this);
        dialouge.setVisible(true);
        
    }//GEN-LAST:event_viewLibraryActionPerformed

	/**
	 * @param args the command line arguments
	 */
	

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton newHall;
    private javax.swing.JButton newLibrary;
    private javax.swing.JButton newPaper;
    private javax.swing.JButton newTutor;
    private javax.swing.JButton viewHall;
    private javax.swing.JButton viewLibrary;
    private javax.swing.JButton viewPaper;
    private javax.swing.JButton viewTutor;
    // End of variables declaration//GEN-END:variables
}
