/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.*;
import domain.*;
import gui_helpers.SimpleListModel;
import java.util.Collection;
import java.awt.Window;
import javax.swing.JOptionPane;

/**
 *
 * @author Finley
 */
public class PaperViewer extends javax.swing.JDialog {

    private final PaperDAO dao;
    SimpleListModel paperModel = new SimpleListModel();
    Collection<Paper> papers;

    /**
     * Creates new form Paper viewer
     */
    public PaperViewer(Window parent, boolean modal, PaperDAO dao) {
        super(parent);
        this.dao = dao;
        papers = dao.getPapers();
        initComponents();
        cmbPaperCode.setEditable(true);

        //create a list model for the paper codes to fill the combo box with data
        // as new papers are added
        SimpleListModel paperCodesModel = new SimpleListModel();
        Collection<String> paperCodes = dao.getPaperCodes();
        paperCodesModel.updateItems(paperCodes);
        cmbPaperCode.setModel(paperCodesModel);

        //create a list model for the departments to fill the combo box with data
        // as new papers are added
        SimpleListModel departmentsModel = new SimpleListModel();
        Collection<String> departments = dao.getDepartments();
        departmentsModel.updateItems(departments);
        cmbDepartment.setModel(departmentsModel);

        //updates the paper model and adds them to the gui to display them
        paperModel.updateItems(papers);
        lstPapers.setModel(paperModel);

        //set names of gui components
        btnEdit.setName("btnEdit");
        btnDelete.setName("btnDelete");
        lstPapers.setName("papersList");
        btnSearchById.setName("btnSearch");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstPapers = new javax.swing.JList<>();
        btn = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtSearchById = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSearchById = new javax.swing.JButton();
        cmbPaperCode = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmbDepartment = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(lstPapers);

        btn.setText("Close");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.setName("btnDelete"); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel1.setText("Search By ID");

        txtSearchById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchByIdActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.setName("btnDelete"); // NOI18N
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        jLabel2.setText("Search By Code");

        btnSearchById.setText("Search");
        btnSearchById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByIdActionPerformed(evt);
            }
        });

        cmbPaperCode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPaperCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPaperCodeActionPerformed(evt);
            }
        });

        jLabel3.setText("Filter By Department");

        cmbDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDepartmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                        .addGap(43, 43, 43)
                        .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSearchById)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearchById))
                            .addComponent(cmbPaperCode, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbDepartment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSearchById, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchById))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbPaperCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn)
                    .addComponent(btnDelete)
                    .addComponent(btnEdit))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        Paper paper = lstPapers.getSelectedValue();

        //if a paper is selected, asks user if they are sure they want to delete the paper, updates the paper model if pressed confirm
        if (!(lstPapers.isSelectionEmpty())) {
            int confirm = JOptionPane.showConfirmDialog(this, "Delete Paper: \nID:" + paper.getPaperId() + "\nCode: " + paper.getCode() + "\nName: " + paper.getTitle() + "\nConfirm: ");
            if (confirm == JOptionPane.YES_OPTION) {
                dao.deletePaper(paper);
                paperModel.updateItems(dao.getPapers());
            }
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtSearchByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchByIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchByIdActionPerformed


    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed

        //if no paper is selected when edit button pressed, do nothing
        if (lstPapers.isSelectionEmpty()) {
            return;
        }

        // get selected paper from list
        Paper selectedPaper = lstPapers.getSelectedValue();

        //creates a new dialog window
        PaperEditor dialog = new PaperEditor(this, true, selectedPaper, dao);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

        // update list to display new paper details
        paperModel.updateItems(dao.getPapers());

    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSearchByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByIdActionPerformed

        //gets the data typed into the search field and updates the model with the matching results
        String id = txtSearchById.getText();
        Paper paper = dao.searchByPaperID(id);
        paperModel.updateItems(paper);
    }//GEN-LAST:event_btnSearchByIdActionPerformed


    private void cmbPaperCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPaperCodeActionPerformed

        //gets selected papercode and updates model with paper that matches input
        String paperCodes = (String) cmbPaperCode.getSelectedItem();
        paperModel.updateItems(dao.filterByPaperCode(paperCodes));

    }//GEN-LAST:event_cmbPaperCodeActionPerformed

    private void cmbDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDepartmentActionPerformed

        //returns all papers with the selected department
        String departments = (String) cmbDepartment.getSelectedItem();
        paperModel.updateItems(dao.filterByDepartment(departments));
    }//GEN-LAST:event_cmbDepartmentActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSearchById;
    private javax.swing.JComboBox<String> cmbDepartment;
    private javax.swing.JComboBox<String> cmbPaperCode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Paper> lstPapers;
    private javax.swing.JTextField txtSearchById;
    // End of variables declaration//GEN-END:variables
}
